"""empty message

Revision ID: 87aa77b18d13
Revises: 44ebc8bbd29f
Create Date: 2023-07-01 21:51:53.299422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aa77b18d13'
down_revision = '44ebc8bbd29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('lat', sa.String(length=80), nullable=False))
        batch_op.drop_column('ubication_image')
        batch_op.drop_column('area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ubication_image', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('lat')
        batch_op.drop_column('lng')

    # ### end Alembic commands ###
